language: python
python:
  - 2.7
branches:
  only:
    - master
    - development

# Setup anaconda in a new virtual environment
before_install:
  - sudo add-apt-repository -y ppa:team-electronics/ppa
  - sudo apt-get update -qq
  - wget http://repo.continuum.io/archive/Anaconda-2.1.0-Linux-x86_64.sh -O anaconda.sh
  - chmod +x anaconda.sh
  - ./anaconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  - conda update --yes conda
  - conda update --yes anaconda
#  - conda create --yes -n anacondaenv python=$TRAVIS_PYTHON_VERSION
#  - source activate anacondaenv
  - wget -O cocotb-master.zip https://github.com/potentialventures/cocotb/archive/master.zip 
  - unzip cocotb-master.zip
  - export COCOTB=$(pwd)/cocotb-master
  - cd host
# The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - set
# Install pybar with needed packages
install:
  - pip install https://github.com/walac/pyusb/archive/master.zip
  - pip install https://silab-redmine.physik.uni-bonn.de/attachments/download/695/pySiLibUSB-2.0.2.tar.gz
  - pip install https://silab-redmine.physik.uni-bonn.de/attachments/download/719/Basil-2.0.2.tar.gz
  - pip install progressbar-latest
  - sudo apt-get install -qq iverilog-daily
  #  Build iverilog from source
#  - sudo apt-get install gperf
#  - wget -O iverilog-master.zip  https://github.com/steveicarus/iverilog/archive/master.zip
#  - unzip iverilog-master.zip
#  - cd iverilog-master && autoconf && ./configure && make && sudo make install && cd ..
  # Install pybar
  - python setup.py develop
# Run test
script:
- cd tests; nosetests test_analysis.py test_interface.py --logging-level=INFO
